### ISSUE TITLE
libcamera-still signal and keypress modes don't allow for capturing multiple frames like raspistill

### ISSUE THREAD

**Issue by dustinkerstein** [raspberrypi/libcamera-apps#152]
We had an app built around raspistill's ability to capture frames quickly when SIGUSR1 was received. This worked great. It seems like libcamera-still has similar functionality, but it quits upon the first received signal (or keypress). I'm sure I could hack the source, but I was just curious, is that the intended behavior or should it have parity with raspistill?

**Comment by davidplowman** [comment]
Hi, thanks for reporting this. Actually we have already fixed this problem here: https://github.com/raspberrypi/libcamera-apps/pull/143
We'll make sure it gets into the next update of our apt repositories, probably "in a few days".

**Comment by dustinkerstein** [comment]
Awesome! Thanks. I'll go ahead and close this issue.

**Comment by byWulf** [comment]
@davidplowman Hey David, can you aproximately say how long it will take until this fix is in the apt repository available? I am still getting the version vom 2021-10-21 there :/ Thanks!

**Comment by davidplowman** [comment]
Hi again, yes I'm sorry this has been taking so long. We would have updated the apt repositories ages ago but for the problem with the Bullseye kernel being incompatible with recent libcamera code (and in turn libcamera-apps).

However, we are currently testing our Bullseye update image which brings everything back in sync and will resolve all these problems. My expectation is quite strongly that it is likely to happen this week, though of course it's not finally my decision exactly when it gets the final go-ahead.
