### ISSUE TITLE
[ISSUE] libcamerasrc is not working with gst-launch-1.0 command

### ISSUE THREAD

**Issue by ankurrajw** [raspberrypi/libcamera-apps#234]
### Error in creating pipeline with g-streamer and libcamerasrc

Today, I updated my Raspberry Pi model 4b with the new update for libcamera and libcamera-apps (mentioned in bug report attached). I am now not able to create my gstreamer pipeline with libcamerasrc.

The libcamera-apps like libcamera-still and libcamera-vid can access the camera connected to the CSI cable. But I am not able to access the same camera with libcamerasrc.

For my project, I need to access the camera feed inside Open CV for further transformations. The pipeline was previously working for me, but now it is giving the error message.

I was not able to find enough resources for this error, that's why I posted it here.

Thank you for all the help.

### Short description on hardware and software used
For detailed information, see the bug.txt file

** cat /etc/os-release **
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

** libcamera-hello --version **
libcamera-apps build: b9a692385d32 07-01-2022 (16:10:12)
libcamera build: v0.0.0+3384-44d59841

------------------
Cameras
----------------

libcamera-hello` --list-cameras
[0:29:16.483767384] [5254]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3384-44d59841
[0:29:16.498862203] [5255] ERROR CameraSensor camera_sensor.cpp:535 'ov5647 10-0036': Camera sensor does not support test pattern modes.
[0:29:16.519372623] [5255]  INFO RPI raspberrypi.cpp:1313 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media1 and ISP device /dev/media0

------------------
Available cameras
--------------------
0 : ov5647 [2592x1944] (/base/soc/i2c0mux/i2c@1/ov5647@36)
    Modes: 'SGBRG10_CSI2P' : 640x480 1296x972 1920x1080 2592x1944 
           'SGBRG8' : 640x480 

### Command Used

Inside Terminal
`gst-launch-1.0 -v libcamerasrc ! video/x-raw,width=640,height=480,framerate=90/1 ! videoflip method=clockwise ! videoconvert ! autovideosink`

Inside Open CV

``libcamerasrc` ! video/x-raw,width=640,height=480,framerate=90/1 ! videoflip method=clockwise ! videoconvert ! appsink``

### Error

``Setting pipeline to PAUSED ...
[0:29:16.109057821] [5201]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3384-44d59841
[0:29:16.125724912] [5208] ERROR CameraSensor camera_sensor.cpp:535 'ov5647 10-0036': Camera sensor does not support test pattern modes.
[0:29:16.146189795] [5208]  INFO RPI raspberrypi.cpp:1313 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media1 and ISP device /dev/media0
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.564: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed

(gst-launch-1.0:5201): GStreamer-CRITICAL **: 15:40:51.565: gst_value_set_int_range_step: assertion 'start < end' failed
ERROR: from element /GstPipeline:pipeline0/GstLibcameraSrc:libcamerasrc0: Internal data stream error.
Additional debug info:
../src/gstreamer/gstlibcamerasrc.cpp(474): gst_libcamera_src_task_enter (): /GstPipeline:pipeline0/GstLibcameraSrc:libcamerasrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.001762380
Setting pipeline to NULL ...
Freeing pipeline ...``

**Solution Assumption**
I think this error is generated due to the recent update of libcamera libraray causing a driver issue with the camera module. But I am not sure about this.

**Bug report**
[bug.txt](https://github.com/raspberrypi/libcamera-apps/files/7951600/bug.txt)

**Comment by naushir** [comment]
Hi, this issue should already have been fixed in the libcamera library.  To get this fix immediately, you will have to rebuild the libcamera and libcamera-apps libraries from the latest sources.  Instructions can be found [here](https://www.raspberrypi.com/documentation/accessories/camera.html#building-libcamera-and-libcamera-apps).

**Comment by ankurrajw** [comment]
Thank you for the response. I will rebuild the libcamera libraries.

**Comment by ankurrajw** [comment]
I have just recompiled the project and the pipeline works !
But I am still getting these ERROR and INFO messages for my Raspberry Pi camera zero(ov5647).

`[1558] ERROR CameraSensor camera_sensor.cpp:551 'ov5647 10-0036': Camera sensor does not support test pattern modes.
[0:02:17.231269258] [1558]  INFO RPI raspberrypi.cpp:1326 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media3 and ISP device /dev/media0
`

Out of curiosity, can you please tell what could be the reason behind it ? 
Is it something related to my hardware being not supported to do functions like autofocus or brightness control through command line ?

Thank you again.

**Comment by naushir** [comment]
You can safely ignore this message.  It's informing us that the sensor driver has no support for test patters to be generated.  This is not related to normal camera operation.

**Comment by ankurrajw** [comment]
Okay thanks again.
